#!/bin/bash

echo "Running WartRemover..."
sbt "Test / compile"
git add -u
#sbt scalafmt
#sbt wartremover
#sbt clean coverage test
#sbt coverageReport
#sbt doc

#shellcheck disable=SC2181
if [ $? -ne 0 ]; then
  echo "WartRemover found issues. Please fix them before committing."
  exit 1
fi
echo "All checks passed!"
